// 더미 데이터 리스트
const dummyIdols = [
  {
    id: 1,
    name: '아이돌1',
    group: '그룹1',
    image: '/assets/images/profile.png',
  },
  {
    id: 2,
    name: '아이돌2',
    group: '그룹1',
    image: '/assets/images/profile.png',
  },
  {
    id: 3,
    name: '아이돌3',
    group: '그룹1',
    image: '/assets/images/profile.png',
  },
  {
    id: 4,
    name: '아이돌4',
    group: '그룹1',
    image: '/assets/images/profile.png',
  },
  {
    id: 5,
    name: '아이돌5',
    group: '그룹2',
    image: '/assets/images/profile.png',
  },
  {
    id: 6,
    name: '아이돌6',
    group: '그룹2',
    image: '/assets/images/profile.png',
  },
  {
    id: 7,
    name: '아이돌7',
    group: '그룹2',
    image: '/assets/images/profile.png',
  },
  {
    id: 8,
    name: '아이돌8',
    group: '그룹2',
    image: '/assets/images/profile.png',
  },
  {
    id: 9,
    name: '아이돌9',
    group: '그룹3',
    image: '/assets/images/profile.png',
  },
  {
    id: 10,
    name: '아이돌10',
    group: '그룹3',
    image: '/assets/images/profile.png',
  },
  {
    id: 11,
    name: '아이돌11',
    group: '그룹3',
    image: '/assets/images/profile.png',
  },
  {
    id: 12,
    name: '아이돌12',
    group: '그룹3',
    image: '/assets/images/profile.png',
  },
  {
    id: 13,
    name: '아이돌13',
    group: '그룹4',
    image: '/assets/images/profile.png',
  },
  {
    id: 14,
    name: '아이돌14',
    group: '그룹4',
    image: '/assets/images/profile.png',
  },
  {
    id: 15,
    name: '아이돌15',
    group: '그룹4',
    image: '/assets/images/profile.png',
  },
  {
    id: 16,
    name: '아이돌16',
    group: '그룹4',
    image: '/assets/images/profile.png',
  },
  {
    id: 17,
    name: '아이돌17',
    group: '그룹5',
    image: '/assets/images/profile.png',
  },
  {
    id: 18,
    name: '아이돌18',
    group: '그룹5',
    image: '/assets/images/profile.png',
  },
  {
    id: 19,
    name: '아이돌19',
    group: '그룹5',
    image: '/assets/images/profile.png',
  },
  {
    id: 20,
    name: '아이돌20',
    group: '그룹5',
    image: '/assets/images/profile.png',
  },
  {
    id: 21,
    name: '아이돌21',
    group: '그룹6',
    image: '/assets/images/profile.png',
  },
  {
    id: 22,
    name: '아이돌22',
    group: '그룹6',
    image: '/assets/images/profile.png',
  },
  {
    id: 23,
    name: '아이돌23',
    group: '그룹6',
    image: '/assets/images/profile.png',
  },
  {
    id: 24,
    name: '아이돌24',
    group: '그룹6',
    image: '/assets/images/profile.png',
  },
  {
    id: 25,
    name: '아이돌25',
    group: '그룹7',
    image: '/assets/images/profile.png',
  },
  {
    id: 26,
    name: '아이돌26',
    group: '그룹7',
    image: '/assets/images/profile.png',
  },
  {
    id: 27,
    name: '아이돌27',
    group: '그룹7',
    image: '/assets/images/profile.png',
  },
  {
    id: 28,
    name: '아이돌28',
    group: '그룹7',
    image: '/assets/images/profile.png',
  },
  {
    id: 29,
    name: '아이돌29',
    group: '그룹8',
    image: '/assets/images/profile.png',
  },
  {
    id: 30,
    name: '아이돌30',
    group: '그룹8',
    image: '/assets/images/profile.png',
  },
  {
    id: 31,
    name: '아이돌31',
    group: '그룹8',
    image: '/assets/images/profile.png',
  },
  {
    id: 32,
    name: '아이돌32',
    group: '그룹8',
    image: '/assets/images/profile.png',
  },
];

export default dummyIdols;
